# Generated by Django 5.0.7 on 2024-07-09 18:30

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                max_length=14, unique=True, validators=[users.validators.validate_cpf]
            ),
        ),
    ]
