# Generated by Django 4.2.11 on 2024-07-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_id",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
